********************************
*                              *
*  GBBS Pro - Config Program   *
*                              *
********************************
 Date
********************************

 rel
 dsk rel/config

 lst off
 put equates
 put start
 put routine
 put disk
 put pdiskio
 put ospjunk
 put viddvr
 put modem
 put video
 put clock
 put printer
 put init
 put pfilter
 put pstor
 put boardedit
 put user
 put userpurge
