 org $2000 ; org to where you want it
 typ $ff
 LKV $00

 link rel/config
 link rel/initstr
 link modems/rel/nullmdm
 link modems/rel/cat103
 link modems/rel/cat212
 link modems/rel/mm2
 link modems/rel/ssc
 link modems/rel/gsport1
 link modems/rel/gsport2
 link modems/rel/gsport1.hst
 link modems/rel/gsport2.hst
 link modems/rel/ultra1
 link modems/rel/ultra2
 link modems/rel/singlespd
 link modems/rel/multispd
 link modems/rel/nocar

 link video/rel/apple40
 link video/rel/apple80
 link video/rel/apple40pl
 link video/rel/videx

 link clocks/rel/gsclock
 link clocks/rel/null
 link clocks/rel/thunder
 link clocks/rel/serialpro
 link clocks/rel/iicsys
 link clocks/rel/versa
 link clocks/rel/noslot
 link clocks/rel/prodos
 link clocks/rel/mountain
 link clocks/rel/ultra

 link printers/rel/null
 link printers/rel/parallel
 link printers/rel/serial
 link printers/rel/grappler
 sav CONFIG.SYSTEM
