 PAG
********************************
*                              *
* ACOS.OBJ - Profanity Filter  *
*                              *
********************************
 DATE
*-------------------------------

FILTER DCI 'FUCK'
 DCI 'SHIT'
 DCI 'DAMN'
 DCI 'ASSHOLE'
 DCI 'COCK'
 DCI 'SUCK'
 DCI 'PRICK'
 DB 00
 DB cr
 ASC 'GBBS Pro V:2.20 (C) 1986-2019 by Kevin M. Smallwood   '0D
* ASC 'GBBS Pro V:2.20 (C) 1986-1989 by L&L Productions, Inc.'0D
* ASC 'GBBS Pro V:1.4 (C) 1986-1989 by L & L Productions'0D
* ASC 'Lance Taylor-Warren, fixes by A.Wells & L.Roathe'0D00
 DS \
